name: Main Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches: [main]
        types: [opened, synchronize]

jobs:
    full-pipeline:
        runs-on: 'ubuntu-18.04'
        steps:
            - uses: 'actions/checkout@v2'
              with:
                  fetch-depth: '0'
            - uses: 'actions/setup-node@v1'
              with:
                  node-version: '12.x'
            - name: npm install
              run: npm install
            - name: lint
              run: npm run lint
            - uses: 'actions/checkout@v2'
            - name: Bump version and push tag
              uses: anothrNick/github-tag-action@1.34.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  DEFAULT_BUMP: patch
                  INITIAL_VERSION: 2.0.0
                  WITH_V: true
              if: (github.event_name == 'push') && !contains(github.event.head_commit.message, '#skip') && success()
